# Conexão com o banco (com a correção da chave pública)
spring.datasource.url=jdbc:mysql://localhost:3306/meu_banco_de_dados?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=usuario_admin
spring.datasource.password=senha_admin

# Configurações do ORM (Hibernate)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# O Flyway roda automaticamente ao iniciar o app
spring.flyway.enabled=true

# Desliga o banner do Spring e logs desnecessários no terminal
spring.main.banner-mode=off
logging.level.root=WARN